### PR TITLE
[WIP] Role skeleton updates #21 and #40

### PR DESCRIPTION
**Pull request by alikins**
##### SUMMARY
Covering parts of #21 and #40

##### ISSUE TYPE

 - Feature Pull Request
 - Bugfix Pull Request

##### GALAXY CLI VERSION

```
Ansible Galaxy CLI, version0.1.0
Linux, newswoop, 4.16.6-202.fc27.x86_64, #1 SMP Wed May 2 00:09:32 UTC 2018, x86_64
3.6.5 (default, Apr  4 2018, 15:01:18) 
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]/home/adrian/venvs/galaxy-cli-py3/bin/python
Using /home/adrian/.ansible/mazer.yml as config file

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by chouseknecht — DISMISSED** [review]
In `meta/main.yml` the new `role_name` attribute has been added.  From the way it's added, it appears as though it's required, when in fact it's not required. The role name defaults to repository name, and the `role_name` attribute in metadata is an optional way to override this. Please add comments to this effect, letting the user know the purpose of the attribute, and that it's optional.

**Comment by chouseknecht** [comment]
@alikins 

There were some APB templates changes introduced a week ago by: https://github.com/ansible/ansible/pull/41559

Please port the above changes to Mazer.

**Comment by alikins** [comment]
@chouseknecht re https://github.com/ansible/mazer/pull/82#pullrequestreview-130797530 

 See https://github.com/ansible/mazer/pull/82/commits/122d7997e4a5e845af3e00440837024b3754b9b5

**Comment by alikins** [comment]
https://github.com/ansible/mazer/pull/82/commits/99bf20d57b4be90512403b1a7cf9c98295d25f38 resolves https://github.com/ansible/mazer/pull/82#issuecomment-399101441

**Pull request merged**
